name: Trunk Check

on:
  pull_request:
    branches: [main]
    paths-ignore:
      - "**/*.tf"
      - "**/*.tfvars"

# Disable permissions for all available scopes.
permissions: {}

concurrency:
  group: ${{ github.workflow }}-${{ github.repository }}
  cancel-in-progress: true

jobs:
  trunk-check:
    name: Trunk Check
    runs-on: ubuntu-24.04
    permissions:
      contents: read
      checks: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - name: Trunk Check
        uses: trunk-io/trunk-action@2eaee169140ec559bd556208f9f99cdfdf468da8
        with:
          arguments: --filter -tflint,-terraform
